1:
	echo "Step 1: renaming files"
	python 1.renameFiles.py

2:
	echo "Step 2: generating file list"
	python 2.listFilesAndCodeConds.py

3:
	echo "Step 3: assign splicings"
	python 3.assignSplicing.py

4:
	echo "Step 4: generate splice pattern file for Praat"
	python 4.genSplicePattern.py
